[package]
name = "shell"
version = "0.1.0"
edition = "2024" 

[dependencies]
path-clean = "1.0"
rustyline = "17.0.1"
rustyline-derive = "0.11.1"
whoami = "1.6.1"
clearscreen = "2.0"
chrono = "0.4.41"
libc = "0.2.175"
users = "0.11.0"
chrono-tz = "0.10.4"
term_size = "0.3.2"
